In [1]:
import pandas as pd

In [10]:
classic_stats = pd.read_csv('data/classic_stats.csv')
statcast = pd.read_csv('data/statcast.csv')

In [11]:
classic_stats

,last_name,first_name,year,player_age,b_ab,b_total_pa,b_total_hits,b_single,b_double,b_triple,...,b_strikeout,b_walk,b_k_percent,b_bb_percent,batting_avg,slg_percent,on_base_percent,on_base_plus_slg,woba,Unnamed: 20
0,Beltran,Carlos,2017,40,467,509,108,65,29,0,...,102,33,20.0,6.5,0.231,0.383,0.283,0.666,0.283,NaN
1,Pujols,Albert,2017,37,593,636,143,103,17,0,...,93,37,14.6,5.8,0.241,0.386,0.286,0.672,0.286,NaN
2,Mauer,Joe,2017,34,525,597,160,116,36,1,...,83,66,13.9,11.1,0.305,0.417,0.384,0.801,0.349,NaN
3,Cabrera,Miguel,2017,34,469,529,117,79,22,0,...,110,54,20.8,10.2,0.249,0.399,0.329,0.728,0.313,NaN
4,Phillips,Brandon,2017,36,572,604,163,115,34,1,...,73,21,12.1,3.5,0.285,0.416,0.318,0.734,0.316,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
845,Albies,Ozzie,2018,21,639,684,167,98,40,5,...,116,36,17.0,5.3,0.261,0.452,0.304,0.756,0.324,NaN
846,Chapman,Matt,2018,25,547,616,152,80,42,6,...,146,58,23.7,9.4,0.278,0.508,0.356,0.864,0.370,NaN
847,Hoskins,Rhys,2018,25,558,660,137,65,38,0,...,150,87,22.7,13.2,0.246,0.496,0.353,0.849,0.364,NaN
848,Schwarber,Kyle,2018,25,428,510,102,59,14,3,...,140,78,27.5,15.3,0.238,0.467,0.355,0.822,0.343,NaN
849,Moncada,Yoan,2018,23,578,650,136,81,32,6,...,217,67,33.4,10.3,0.235,0.400,0.314,0.714,0.311,NaN